import React, {useEffect, useState} from 'react';
import {Activity, ArrowLeft, Download, RefreshCw, Search, ShieldCheck, Sparkles} from 'lucide-react';
import {useApp} from '../../context/AppContext';
import {apiClient, extractErrorMessage} from '../../lib/api';
import {todayNepal} from '../../lib/posApi';
import {useOutletEvents} from '../../lib/useOutletEvents';
import {AdminAudienceTab} from './AdminAudienceTab';

type Row = Record<string, any>;
const tabs=['Overview','Funnel','Live Users','User Journeys','Campaigns','Ads','Products','Cart Analysis','Checkout Analysis','Payment Analysis','Abandoned Orders','Errors','Performance','Locations','Device Analysis','Event Debugger','Tracking Health','AI Diagnosis','Traffic history'] as const;
type Tab=typeof tabs[number];
const control='bg-white dark:bg-zinc-900 border border-zinc-300 dark:border-zinc-700 rounded px-3 py-2 text-xs';
const panel='bg-white dark:bg-[#121214] border border-zinc-200 dark:border-zinc-800 rounded-lg p-4';
const button=`${control} hover:border-amber-500 disabled:opacity-40 cursor-pointer`;
const label=(key:string)=>key.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const display=(value:any):string=>value===null||value===undefined?'—':typeof value==='number'?value.toLocaleString('en-US',{maximumFractionDigits:2}):typeof value==='object'?JSON.stringify(value):String(value);
const date=(value:string)=>new Date(value).toLocaleString('en-GB',{timeZone:'Asia/Kathmandu',dateStyle:'medium',timeStyle:'medium'});
const metricColumns=['name','sessions','product_viewers','cart','checkout','orders','conversion_percent','errors'];

function DataTable({rows,columns,onSelect,empty='No matching observations yet.'}:{rows:Row[];columns:string[];onSelect?:(row:Row)=>void;empty?:string}) {
  const [sort,setSort]=useState<{key:string;desc:boolean}|null>(null);
  const sorted=sort?[...rows].sort((a,b)=>{const one=a[sort.key],two=b[sort.key];const result=typeof one==='number'&&typeof two==='number'?one-two:String(one??'').localeCompare(String(two??''));return sort.desc?-result:result;}):rows;
  return <div className="overflow-x-auto rounded border border-zinc-200 dark:border-zinc-800"><table className="w-full text-xs text-left"><thead className="bg-zinc-100 dark:bg-zinc-900"><tr>{columns.map(key=><th key={key} className="p-3 whitespace-nowrap"><button onClick={()=>setSort(old=>({key,desc:old?.key===key?!old.desc:true}))}>{label(key)}{sort?.key===key?(sort.desc?' ↓':' ↑'):''}</button></th>)}{onSelect&&<th className="p-3">Journey</th>}</tr></thead><tbody>{sorted.map((row,index)=><tr key={row.id||index} className="border-t border-zinc-200 dark:border-zinc-800">{columns.map(key=><td key={key} className="p-3 max-w-xs break-words">{display(row[key])}{key.endsWith('_percent')&&row[key]!=null?'%':''}</td>)}{onSelect&&<td className="p-3"><button className="text-amber-500 underline whitespace-nowrap" onClick={()=>onSelect(row)}>View journey</button></td>}</tr>)}{!rows.length&&<tr><td colSpan={columns.length+(onSelect?1:0)} className="p-8 text-center text-zinc-500">{empty}</td></tr>}</tbody></table></div>;
}
function Findings({rows}:{rows:Row[]}) {
  return <div className="space-y-3">{rows.map((row,index)=><article key={index} className={`${panel} border-l-4 ${row.kind==='FACT'?'border-l-rose-500':row.kind==='SIGNAL'?'border-l-amber-500':'border-l-sky-500'}`}>
    <div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold text-sm">{row.title}</h3><span className="text-[10px] font-mono">{row.kind} · {row.severity} · {row.confidence} confidence</span></div>
    <p className="text-xs mt-2 text-zinc-500 dark:text-zinc-400"><strong>Evidence:</strong> {row.evidence}</p>
    <p className="text-xs mt-2"><strong>What to fix or investigate:</strong> {row.action}</p>
    <p className="text-xs mt-2 text-zinc-500 dark:text-zinc-400"><strong>Verify:</strong> {row.verification}</p>
  </article>)}</div>;
}

export function ConversionIntelligence() {
  const {currentOutlet}=useApp();const outlet=String(currentOutlet?.id||'');
  const [tab,setTab]=useState<Tab>('Overview');
  const [filters,setFilters]=useState<Record<string,string>>({start_date:todayNepal(),end_date:todayNepal()});
  const [draftSearch,setDraftSearch]=useState('');
  const [revision,setRevision]=useState(0),[page,setPage]=useState(1),[eventPage,setEventPage]=useState(1);
  const [report,setReport]=useState<Row|null>(null),[reportScope,setReportScope]=useState(''),[error,setError]=useState('');
  const [list,setList]=useState<Row|null>(null),[debug,setDebug]=useState<Row|null>(null);
  const [selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<Row|null>(null),[detailPage,setDetailPage]=useState(1);
  const [question,setQuestion]=useState('Why did we get zero orders today?'),[answer,setAnswer]=useState<Row|null>(null),[askBusy,setAskBusy]=useState(false);
  const [exportKind,setExportKind]=useState('events'),[importStatus,setImportStatus]=useState('');
  const valid=/^\d+$/.test(outlet);
  const query=new URLSearchParams({outlet_id:outlet,...Object.fromEntries(Object.entries(filters).filter(([,value])=>value))}).toString();
  const live=useOutletEvents(outlet,valid,()=>setRevision(n=>n+1),undefined,'analytics');
  useEffect(()=>{const timer=setTimeout(()=>setFilters(old=>({...old,search:draftSearch})),350);return()=>clearTimeout(timer);},[draftSearch]);
  useEffect(()=>{setPage(1);setEventPage(1);setSelected(null);setAnswer(null);},[query]);
  useEffect(()=>{setDetailPage(1);setDetail(null);},[selected]);
  useEffect(()=>{
    if(!valid)return;const abort=new AbortController();let active=true;setError('');
    apiClient.get<Row>(`/customer/intelligence/?${query}`,{signal:abort.signal}).then(data=>{if(active){setReport(data);setReportScope(query);}}).catch(e=>{if(active)setError(extractErrorMessage(e));});
    return()=>{active=false;abort.abort();};
  },[query,revision,valid]);
  useEffect(()=>{
    if(!valid||!['User Journeys','Live Users','Abandoned Orders'].includes(tab))return;
    const abort=new AbortController();let active=true;setList(null);
    apiClient.get<Row>(`/customer/journeys/?${query}&page=${page}${tab==='Live Users'?'&live=true':tab==='Abandoned Orders'?'&abandoned=true':''}`,{signal:abort.signal}).then(data=>{if(active)setList(data);}).catch(e=>{if(active)setError(extractErrorMessage(e));});
    return()=>{active=false;abort.abort();};
  },[query,revision,page,tab,valid]);
  useEffect(()=>{
    if(!valid||tab!=='Event Debugger')return;
    const abort=new AbortController();let active=true;
    apiClient.get<Row>(`/customer/event-debugger/?${query}&page=${eventPage}`,{signal:abort.signal}).then(data=>{if(active)setDebug(data);}).catch(e=>{if(active)setError(extractErrorMessage(e));});
    return()=>{active=false;abort.abort();};
  },[query,revision,eventPage,tab,valid]);
  useEffect(()=>{
    if(!selected)return;const abort=new AbortController();let active=true;
    apiClient.get<Row>(`/customer/journeys/${selected}/?outlet_id=${outlet}&page=${detailPage}`,{signal:abort.signal}).then(data=>{if(active)setDetail(data);}).catch(e=>{if(active)setError(extractErrorMessage(e));});
    return()=>{active=false;abort.abort();};
  },[selected,outlet,detailPage,revision]);
  useEffect(()=>{
    if(!answer?.id||!['PENDING','RUNNING'].includes(answer.status))return;let active=true;
    apiClient.get<Row>(`/customer/analyst/${answer.id}/?outlet_id=${outlet}`).then(data=>{if(active)setAnswer(data);}).catch(e=>{if(active)setError(extractErrorMessage(e));});
    return()=>{active=false;};
  },[revision,answer?.id,outlet]);
  const current=reportScope===query?report:null;
  const data=current?.data;
  const setFilter=(key:string,value:string)=>setFilters(old=>({...old,[key]:value}));
  const openJourney=(row:Row)=>{setSelected(row.session_id || row.id);setTab('User Journeys');};
  const ask=async()=>{if(!current?.id)return;setAskBusy(true);setError('');try{setAnswer(await apiClient.post<Row>(`/customer/analyst/?outlet_id=${outlet}`,{report_id:current.id,question}));}catch(e){setError(extractErrorMessage(e));}finally{setAskBusy(false);}};
  const download=async(format:string)=>{try{const result=await apiClient.get<any>(`/customer/intelligence-export/?${query}&kind=${exportKind}&export_format=${format}`);const blob=new Blob([format==='json'?JSON.stringify(result,null,2):result],{type:format==='json'?'application/json':'text/csv'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`analytics-${exportKind}.${format}`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(extractErrorMessage(e));}};
  const importAds=async(file:File|undefined)=>{if(!file)return;setImportStatus('');try{if(file.size>1000000)throw new Error('Choose a JSON file smaller than 1 MB.');const rows=JSON.parse(await file.text());const result=await apiClient.post<Row>(`/customer/ad-metrics/?outlet_id=${outlet}`,rows);setImportStatus(`${result.imported} ad rows imported.`);setRevision(n=>n+1);}catch(e){setError(extractErrorMessage(e));}};
  const group=(name:string)=>data?.groups?.[name]||[];
  return <section className="space-y-4" aria-label="Conversion intelligence">
    <header className="flex flex-wrap justify-between gap-3 items-start"><div><div className="flex items-center gap-2 text-amber-500 text-[10px] uppercase tracking-widest"><Activity size={13}/> Website Analytics · {live?'Live connection':'Reconnecting'}</div><h1 className="text-2xl font-bold mt-1">From click to confirmed order</h1><p className="text-xs text-zinc-500 mt-1">{currentOutlet?.name} · Understand what happened, what stopped customers, and what to test next.</p></div><button className={`${button} flex gap-2 items-center`} onClick={()=>{setRevision(n=>n+1);}}><RefreshCw size={14}/> Refresh data</button></header>
    <div className={`${panel} space-y-3`}>
      <div className="flex flex-wrap gap-3 items-end"><label className="text-xs">From · Nepal time<input aria-label="Analytics start date" type="date" className={`${control} block mt-1`} value={filters.start_date} onChange={e=>setFilter('start_date',e.target.value)}/></label><label className="text-xs">To<input aria-label="Analytics end date" type="date" className={`${control} block mt-1`} value={filters.end_date} onChange={e=>setFilter('end_date',e.target.value)}/></label><label className="text-xs flex-1 min-w-48">Find a session, anonymous visitor, order, campaign or product<input aria-label="Search analytics" value={draftSearch} onChange={e=>setDraftSearch(e.target.value)} className={`${control} block mt-1 w-full`} placeholder="Session ID / order number / product"/></label><button className="rounded border border-amber-600 bg-amber-500 px-3 py-2 text-xs text-black font-semibold hover:bg-amber-400" onClick={()=>{setFilters({start_date:todayNepal(),end_date:todayNepal()});setDraftSearch('');setTab('AI Diagnosis');setRevision(n=>n+1);}}>Diagnose Today's Conversion</button></div>
      <details><summary className="text-xs cursor-pointer text-zinc-500">Segment filters · source, campaign, ad, device, location and checkout</summary><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-3">{['source','medium','campaign','adset','ad','device','browser','os','location','product','category','order_status','payment_method'].map(key=><label key={key} className="text-[11px]">{label(key)}<input className={`${control} block w-full mt-1`} aria-label={`Filter ${key}`} value={filters[key]||''} onChange={e=>setFilter(key,e.target.value)}/></label>)}<label className="text-[11px]">Visitor type<select aria-label="Visitor type" className={`${control} block w-full mt-1`} value={filters.returning||''} onChange={e=>setFilter('returning',e.target.value)}><option value="">All</option><option value="new">New</option><option value="returning">Returning</option></select></label>{['start_time','end_time'].map(key=><label key={key} className="text-[11px]">{label(key)}<input className={`${control} block w-full mt-1`} type="time" value={filters[key]||''} onChange={e=>setFilter(key,e.target.value)}/></label>)}</div></details>
    </div>
    <nav aria-label="Analytics sections" className="flex gap-1.5 overflow-x-auto pb-2">{tabs.map(name=><button key={name} onClick={()=>{setTab(name);setSelected(null);setPage(1);}} className={`${button} whitespace-nowrap ${tab===name?'border-amber-500 text-amber-500':''}`} aria-current={tab===name?'page':undefined}>{name}</button>)}</nav>
    {error&&<div role="alert" className={`${panel} text-rose-500`}>{error}</div>}
    {current?.status==='FAILED'&&<p role="alert" className={`${panel} text-rose-500`}>The analytics worker could not build this report. Existing orders are unaffected. Check the worker logs and retry the report job.</p>}
    {!data&&tab!=='Traffic history'&&<div role="status" className={panel}>{current?.status==='PENDING'||current?.status==='RUNNING'?'Preparing your conversion report. It will appear automatically when the analytics worker finishes.':'Loading analytics…'}<p className="text-xs text-zinc-500 mt-2">If this does not finish, the backend Celery worker and Beat scheduler must be running.</p></div>}
    {data&&<>
      {data.truncated&&<p role="alert" className="text-amber-500">This report reached its event limit. Narrow the date range before drawing conclusions. Event exports and session search remain available.</p>}
      <p className="text-[11px] text-zinc-500">{data.scope_note} Updated {date(data.generated_at)}.</p>
      {tab==='Overview'&&<>
        <div className="grid grid-cols-2 lg:grid-cols-5 gap-2">{[['Ad spend',data.executive.spend],['Ad clicks',data.executive.clicks],['Website visitors',data.executive.visitors],['Sessions',data.executive.sessions],['Add to cart',data.executive.cart],['Checkout',data.executive.checkout],['Tracked orders',data.executive.orders],['Order value · NPR',data.executive.revenue],['Conversion %',data.executive.conversion_percent],['Cost / order',data.executive.cost_per_order]].map(([name,value])=><div key={String(name)} className={panel}><p className="text-xs text-zinc-500">{name}</p><p className="text-2xl font-mono font-bold mt-2">{display(value)}</p>{value==null&&<p className="text-[10px] text-zinc-500 mt-1">Not available for this selection</p>}</div>)}</div>
        <h2 className="font-semibold">What should I investigate first?</h2><Findings rows={data.diagnosis.slice(0,1)}/>
        <h2 className="font-semibold">Where did users drop?</h2><Funnel rows={data.core_funnel}/>
        <div className={panel}><h2 className="font-semibold mb-2">Orders and tracking are different measurements</h2><p className="text-sm">Database website orders: <strong>{data.reconciliation.database_orders}</strong> · Linked purchases: <strong>{data.reconciliation.analytics_purchases}</strong> · Verified paid orders: <strong>{data.reconciliation.verified_paid_orders}</strong></p><p className="text-xs text-zinc-500 mt-2">{data.reconciliation.scope}</p></div>
        <h2 className="font-semibold">Traffic quality</h2><DataTable rows={group('intent')} columns={metricColumns}/>
        <h2 className="font-semibold">Common paths</h2><DataTable rows={data.paths} columns={['path','sessions','percent']}/>
        <h2 className="font-semibold">Time of day · Nepal time</h2><DataTable rows={data.hourly.filter((r:Row)=>r.sessions)} columns={['hour','sessions','cart','orders']}/>
      </>}
      {tab==='Funnel'&&<><p className="text-xs text-zinc-500">The complete journey contains optional steps. QR payment is verified after order submission; zero events at an unavailable step do not prove abandonment. Transition rates require the next event to occur after the previous event.</p><Funnel rows={data.funnel}/><DataTable rows={data.funnel} columns={['stage','users','events','sessions','conversion_percent','previous_step_conversion_percent','drop_off_percent','average_seconds_to_next']}/></>}
      {['User Journeys','Live Users','Abandoned Orders'].includes(tab)&&!selected&&<><h2 className="font-semibold">{tab} <span className="text-xs text-zinc-500">{list?.count??'…'} matching sessions</span></h2><DataTable rows={list?.results||[]} columns={['id','source','campaign','device','status','last_step','cart_value','reason']} onSelect={openJourney}/><Pager page={page} count={list?.count||0} size={25} change={setPage}/><p className="text-xs text-zinc-500">Abandonment is inferred after 30 minutes without activity. A recorded error is evidence of friction, not proof of the reason for leaving.</p></>}
      {selected&&<div className="space-y-3"><button className={`${button} flex gap-2 items-center`} onClick={()=>setSelected(null)}><ArrowLeft size={14}/> Back to sessions</button>{detail&&<><div className={panel}><h2 className="font-semibold">User Journey · {selected.slice(0,8)}</h2><p className="text-xs mt-2">{detail.session.source} · {detail.session.campaign} · {detail.session.device} / {detail.session.browser} · {detail.session.status}</p><p className="text-xs text-zinc-500 mt-2">First visit {date(detail.visitor_first_seen)} · {detail.visitor_session_count} sessions · {detail.session.duration_seconds}s observed · Cart NPR {display(detail.session.cart_value)}</p><details className="mt-3 text-xs"><summary className="cursor-pointer">First / session / last-touch attribution</summary><pre className="overflow-auto mt-2">{JSON.stringify({first:detail.session.first_touch,session:detail.session.session_touch,last:detail.session.last_touch},null,2)}</pre></details></div><EventTimeline events={detail.events}/><Pager page={detailPage} count={detail.count} size={100} change={setDetailPage}/><p className="text-xs text-zinc-500">Recorded-event timeline. Screen recording is unavailable because no session-replay provider is configured.</p></>}</div>}
      {tab==='Campaigns'&&<><h2 className="font-semibold">Source → order</h2><DataTable rows={group('source')} columns={metricColumns}/><h2 className="font-semibold">Campaigns · session attribution</h2><DataTable rows={group('campaign')} columns={metricColumns}/><h2 className="font-semibold">New and returning visitors</h2><DataTable rows={group('returning').map((r:Row)=>({...r,name:r.name==='True'?'Returning':'New'}))} columns={metricColumns}/></>}
      {tab==='Ads'&&<><p className="text-xs text-zinc-500">Sessions with an ad identifier are observed arrivals, not Meta click totals. Import daily Meta reporting to compare impressions, clicks and spend. Imports replace the same date/source/ad row; they do not add duplicates.</p><DataTable rows={group('ad')} columns={metricColumns}/><h2 className="font-semibold">Ad sets</h2><DataTable rows={group('adset')} columns={metricColumns}/><h2 className="font-semibold">Imported advertising metrics</h2><DataTable rows={data.ads} columns={['date','source','campaign_id','adset_id','ad_id','impressions','clicks','spend']}/><label className={`${panel} block text-xs`}>Import daily ad metrics · JSON<input aria-label="Import ad metrics" type="file" accept="application/json,.json" className="block mt-2" onChange={e=>void importAds(e.target.files?.[0])}/><code className="block overflow-auto mt-3">{'[{"date":"YYYY-MM-DD","source":"facebook","campaign_id":"…","adset_id":"…","ad_id":"…","impressions":0,"clicks":0,"spend":"0.00"}]'}</code></label>{importStatus&&<p role="status">{importStatus}</p>}</>}
      {tab==='Products'&&<><p className="text-xs text-zinc-500">Sort columns to compare viewed products and cart/purchase rates. Revenue here is the purchased product line value before order-level discounts.</p><DataTable rows={data.products} columns={['name','view','cart','cart_rate','checkout','purchase','purchase_rate','revenue_before_discounts']}/></>}
      {tab==='Cart Analysis'&&<><DataTable rows={data.cart_bands} columns={['band','cart_sessions','ended_sessions','abandoned','abandonment_percent']}/><div className={panel}><h2 className="font-semibold">Delivery fee exposure</h2><p className="text-sm mt-2">{data.delivery_fees.exposed_sessions} recorded exposures · {data.delivery_fees.abandoned_after_exposure} abandoned sessions after exposure</p><p className="text-xs text-zinc-500 mt-2">{data.delivery_fees.interpretation} The current checkout does not calculate a delivery fee.</p></div></>}
      {tab==='Checkout Analysis'&&<><DataTable rows={data.checkout_fields} columns={['step','sessions']}/><p className="text-xs text-zinc-500">Field events record completion only, never the field value. Location selection is not a serviceability check.</p><DataTable rows={data.errors.filter((r:Row)=>r.event.includes('checkout')||r.event.includes('order')||r.event.includes('delivery'))} columns={['event','category','affected_sessions','events','cart_value_at_risk']}/></>}
      {tab==='Payment Analysis'&&<><p className="text-xs text-zinc-500">Manual QR flow: “payment started” means the customer opened the QR link. External app payments, cancellations and timeouts cannot be observed here. Proof upload is not payment success. Success is recorded when staff verifies full payment.</p><DataTable rows={data.payments} columns={['event_name','timestamp','authority','order_id','metadata']}/></>}
      {tab==='Errors'&&<><p className="text-xs text-zinc-500">Cart value at risk is a snapshot estimate, not proven lost revenue. Select an affected session to inspect the evidence.</p><DataTable rows={data.errors} columns={['event','endpoint','http_status','category','events','affected_sessions','cart_value_at_risk']}/>{data.errors.map((r:Row,index:number)=><details key={index} className={panel}><summary className="text-xs cursor-pointer">{label(r.event)} · {r.affected_sessions} sessions</summary><div className="flex flex-wrap gap-2 mt-2">{r.session_ids.map((id:string)=><button key={id} className={button} onClick={()=>openJourney({id})}>{id.slice(0,8)}</button>)}</div></details>)}</>}
      {tab==='Performance'&&<><p className="text-xs text-zinc-500">LCP, INP, page/DOM and API timing are in milliseconds; CLS is a score. Only browsers that emit a measurement are included.</p><DataTable rows={data.performance} columns={['metric','device','browser','os','network','samples','average','p95']}/></>}
      {tab==='Locations'&&<><p className="text-xs text-zinc-500">Only coarse areas explicitly reported by the application appear here. Exact addresses and map coordinates are never stored in analytics. Unknown means no coarse area was measured.</p><DataTable rows={group('location')} columns={metricColumns}/></>}
      {tab==='Device Analysis'&&<><DataTable rows={group('device')} columns={metricColumns}/><h2 className="font-semibold">Operating systems</h2><DataTable rows={group('os')} columns={metricColumns}/><h2 className="font-semibold">Browsers</h2><DataTable rows={group('browser')} columns={metricColumns}/></>}
      {tab==='Event Debugger'&&<><p className="text-xs text-zinc-500">Live, sanitized event payloads. Browser events are observations; server events confirm orders and payments.</p>{debug?.results?.map((event:Row)=><details key={event.id} className={panel}><summary className="text-xs cursor-pointer">{date(event.received_at)} · {event.event_name} · {event.authority}</summary><button className={`${button} my-2`} onClick={()=>openJourney(event)}>Open session</button><pre className="text-xs overflow-auto">{JSON.stringify(event,null,2)}</pre></details>)}{!debug?.results?.length&&<p className={panel}>No recorded events for this selection.</p>}<Pager page={eventPage} count={debug?.count||0} size={100} change={setEventPage}/></>}
      {tab==='Tracking Health'&&<><div className={`${panel} flex gap-3`}><ShieldCheck className="text-emerald-500 shrink-0"/><div><h2 className="font-semibold">Unknown is different from zero</h2><p className="text-xs mt-1">An unobserved event is not automatically a broken tracker. Privacy opt-outs, unsupported steps and older orders can all reduce coverage.</p></div></div><DataTable rows={data.tracking_health} columns={['event','events','status']}/><DataTable rows={[data.reconciliation]} columns={['database_orders','analytics_purchases','verified_paid_orders','missing_purchase_tracking']}/>{data.duplicates&&<DataTable rows={data.duplicates} columns={['event','identity','events','explanation']}/>}<ul className={`${panel} list-disc pl-8 text-xs space-y-2`}>{data.limitations.map((text:string)=><li key={text}>{text}</li>)}</ul></>}
      {tab==='AI Diagnosis'&&<><div className={panel}><h2 className="font-semibold flex items-center gap-2"><Sparkles size={17} className="text-amber-500"/> Conversion diagnosis</h2><p className="text-xs text-zinc-500 mt-2">Facts come from recorded events and database orders. Signals describe patterns. Hypotheses are possible explanations to test.</p></div><Findings rows={data.diagnosis}/>{data.baseline&&<div className={panel}><h2 className="font-semibold">Previous seven-day baseline</h2><p className="text-sm mt-2">{data.baseline.sessions} sessions · {display(data.baseline.conversion_percent)}% conversion · {data.baseline.significant_decline?'Significant decline detected':'No statistically supported decline detected'}</p><p className="text-xs text-zinc-500 mt-2">{data.baseline.method}</p></div>}<div className={panel}><h2 className="font-semibold mb-3">Ask your data</h2><div className="flex gap-2"><input aria-label="Ask your data" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={300} className={`${control} flex-1 min-w-0`}/><button disabled={askBusy||!question.trim()} className={button} onClick={()=>void ask()}>Ask</button></div><p className="text-[11px] text-zinc-500 mt-2">Works with rules-based evidence immediately. When a server-side AI provider is configured, it selects relevant evidence and existing findings; it cannot create metric values.</p>{answer&&<div className="mt-4 space-y-3">{answer.status!=='READY'?<p role="status">{answer.status==='FAILED'?'The AI request failed. The recorded diagnosis above remains available.':'Analyzing the report in the background…'}</p>:<><h3 className="text-sm font-semibold">{answer.data.mode}</h3><p className="text-xs">{answer.data.answer}</p><DataTable rows={answer.data.evidence} columns={['id','label','value']}/><Findings rows={answer.data.findings}/></>}</div>}</div></>}
    </>}
    {tab==='Traffic history'&&<AdminAudienceTab mode="analytics"/>}
    <footer className="flex flex-wrap gap-2 items-center text-xs border-t border-zinc-200 dark:border-zinc-800 pt-4"><Download size={14}/><span>Export filtered data</span><select aria-label="Export dataset" className={control} value={exportKind} onChange={e=>setExportKind(e.target.value)}>{['events','sessions','funnel','campaigns','abandoned','errors'].map(kind=><option key={kind}>{kind}</option>)}</select><button className={button} onClick={()=>void download('csv')}>CSV</button><button className={button} onClick={()=>void download('json')}>JSON</button></footer>
  </section>;
}

function Pager({page,count,size,change}:{page:number;count:number;size:number;change:(value:number)=>void}) {
  return <div className="flex items-center gap-3 text-xs"><button className={button} disabled={page===1} onClick={()=>change(page-1)}>Previous</button><span>Page {page} of {Math.max(1,Math.ceil(count/size))}</span><button className={button} disabled={page*size>=count} onClick={()=>change(page+1)}>Next</button></div>;
}
function Funnel({rows}:{rows:Row[]}) {
  const maximum=Math.max(1,...rows.map(row=>row.sessions));
  return <div className={`${panel} space-y-3`}>{rows.map((row,index)=><div key={row.stage}><div className="flex justify-between text-xs mb-1"><span>{index+1}. {row.stage}</span><span><strong>{row.sessions}</strong> sessions {row.drop_off_percent!=null&&<span className="text-zinc-500"> · {row.drop_off_percent}% did not advance from previous step</span>}</span></div><div className="h-2 bg-zinc-100 dark:bg-zinc-800 rounded overflow-hidden"><div className="h-full bg-amber-500 rounded" style={{width:`${row.sessions/maximum*100}%`}}/></div></div>)}</div>;
}
function EventTimeline({events}:{events:Row[]}) {
  return <ol className="space-y-2">{events.map((event,index)=><li key={event.id} className={`${panel} border-l-2 border-l-amber-500`}><div className="flex flex-wrap justify-between text-xs gap-2"><strong>{label(event.event_name)}</strong><span className="text-zinc-500">{date(event.timestamp)} {index>0?`· +${Math.max(0,(Date.parse(event.timestamp)-Date.parse(events[index-1].timestamp))/1000).toFixed(1)}s`:''}</span></div><p className="text-xs text-zinc-500 mt-1">{event.page} · {event.authority}{event.order_id?` · Order ${event.order_id}`:''}</p><details className="text-xs mt-2"><summary className="cursor-pointer">Event payload</summary><pre className="overflow-auto mt-2">{JSON.stringify(event.metadata,null,2)}</pre></details></li>)}</ol>;
}
